/** Keep in sync with `apps/api/prisma/schema.prisma` enums */

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  COMPANY_ADMIN = 'COMPANY_ADMIN',
  DISPATCHER = 'DISPATCHER',
  ACCOUNTING = 'ACCOUNTING',
  DRIVER = 'DRIVER',
}

export enum DriverType {
  COMPANY_DRIVER = 'COMPANY_DRIVER',
  OWNER_OPERATOR = 'OWNER_OPERATOR',
}

export enum PayStructure {
  PER_MILE = 'PER_MILE',
  FIXED_SALARY = 'FIXED_SALARY',
  PERCENTAGE = 'PERCENTAGE',
}

export enum LoadStatus {
  PENDING = 'PENDING',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  TONU = 'TONU',
}

export enum SettlementStatus {
  DRAFT = 'DRAFT',
  FINALIZED = 'FINALIZED',
  PAID = 'PAID',
}

export enum DeductionType {
  FUEL = 'FUEL',
  INSURANCE_ESCROW = 'INSURANCE_ESCROW',
  CASH_ADVANCE = 'CASH_ADVANCE',
  MAINTENANCE = 'MAINTENANCE',
  LUMPER = 'LUMPER',
  TOLL = 'TOLL',
  VIOLATION_FINE = 'VIOLATION_FINE',
  COMPANY_FEE = 'COMPANY_FEE',
  OTHER = 'OTHER',
}

export enum CreditType {
  REIMBURSEMENT = 'REIMBURSEMENT',
  BONUS = 'BONUS',
  OTHER = 'OTHER',
}

export enum DocumentType {
  CDL = 'CDL',
  MEDICAL_CARD = 'MEDICAL_CARD',
  DOT_INSPECTION = 'DOT_INSPECTION',
  IRP_REGISTRATION = 'IRP_REGISTRATION',
  FORM_2290 = 'FORM_2290',
  INSURANCE_POLICY = 'INSURANCE_POLICY',
  BILL_OF_LADING = 'BILL_OF_LADING',
  LUMPER_RECEIPT = 'LUMPER_RECEIPT',
  RATE_CONFIRMATION = 'RATE_CONFIRMATION',
  OTHER = 'OTHER',
}

export enum NotificationType {
  COMPLIANCE_WARNING = 'COMPLIANCE_WARNING',
  COMPLIANCE_EXPIRED = 'COMPLIANCE_EXPIRED',
  SETTLEMENT_READY = 'SETTLEMENT_READY',
  LOAD_ASSIGNED = 'LOAD_ASSIGNED',
  SYSTEM = 'SYSTEM',
}

export enum ComplianceStatus {
  GREEN = 'GREEN',
  YELLOW = 'YELLOW',
  RED = 'RED',
}
