import type {
  ComplianceEntityType,
  ComplianceTrackingMode,
} from '@prisma/client';

export interface ComplianceTypeDef {
  key: string;
  label: string;
  category: string;
  entityType: ComplianceEntityType;
  trackingMode: ComplianceTrackingMode;
  defaultCadenceMonths: number | null;
  description?: string;
  sortOrder: number;
  /** When a company has no explicit setting row, this decides visibility. */
  defaultEnabled: boolean;
  /** Maps to the legacy denormalized field used for backfill (if any). */
  legacyField?: 'cdlExpiryDate' | 'medicalCardExpiry' | 'dotInspectionExpiry' | 'irpExpiry' | 'hvutExpiry' | 'insuranceExpiry';
}

export const COMPLIANCE_CATEGORIES = [
  'Licensing',
  'Medical',
  'Drug & Alcohol',
  'Inspection',
  'Registration',
  'Taxes',
  'Permits',
  'Insurance',
  'Maintenance',
  'Authority',
] as const;

/**
 * System catalog of compliance requirement types.
 * Companies can enable/disable and override cadence via CompanyComplianceSetting.
 */
export const COMPLIANCE_CATALOG: ComplianceTypeDef[] = [
  // ─── DRIVER ─────────────────────────────────────────
  {
    key: 'DRIVER_CDL',
    label: 'CDL License',
    category: 'Licensing',
    entityType: 'DRIVER',
    trackingMode: 'EXPIRY',
    defaultCadenceMonths: null,
    description: 'Commercial Driver License expiration.',
    sortOrder: 10,
    defaultEnabled: true,
    legacyField: 'cdlExpiryDate',
  },
  {
    key: 'DRIVER_MEDICAL_CARD',
    label: 'Medical Card (DOT Physical)',
    category: 'Medical',
    entityType: 'DRIVER',
    trackingMode: 'EXPIRY',
    defaultCadenceMonths: 24,
    description: 'DOT medical examiner certificate.',
    sortOrder: 20,
    defaultEnabled: true,
    legacyField: 'medicalCardExpiry',
  },
  {
    key: 'DRIVER_CLEARINGHOUSE',
    label: 'FMCSA Clearinghouse Query',
    category: 'Drug & Alcohol',
    entityType: 'DRIVER',
    trackingMode: 'INTERVAL',
    defaultCadenceMonths: 12,
    description: 'Annual limited query in the FMCSA Drug & Alcohol Clearinghouse.',
    sortOrder: 30,
    defaultEnabled: true,
  },
  {
    key: 'DRIVER_DRUG_TEST',
    label: 'Drug & Alcohol Test',
    category: 'Drug & Alcohol',
    entityType: 'DRIVER',
    trackingMode: 'INTERVAL',
    defaultCadenceMonths: 12,
    description: 'Most recent drug/alcohol test (pre-employment, random, post-accident, etc.).',
    sortOrder: 40,
    defaultEnabled: true,
  },
  {
    key: 'DRIVER_MVR',
    label: 'MVR / Annual Driving Record Review',
    category: 'Licensing',
    entityType: 'DRIVER',
    trackingMode: 'INTERVAL',
    defaultCadenceMonths: 12,
    description: 'Annual Motor Vehicle Record review (§391.25).',
    sortOrder: 50,
    defaultEnabled: true,
  },
  {
    key: 'DRIVER_ANNUAL_REVIEW',
    label: 'Annual Review of Driving Record (§391.27)',
    category: 'Licensing',
    entityType: 'DRIVER',
    trackingMode: 'INTERVAL',
    defaultCadenceMonths: 12,
    description: 'Annual certificate of violations / driving record review.',
    sortOrder: 60,
    defaultEnabled: true,
  },
  {
    key: 'DRIVER_HAZMAT',
    label: 'HazMat Endorsement',
    category: 'Licensing',
    entityType: 'DRIVER',
    trackingMode: 'EXPIRY',
    defaultCadenceMonths: null,
    description: 'Hazardous materials endorsement (if applicable).',
    sortOrder: 70,
    defaultEnabled: false,
  },
  {
    key: 'DRIVER_TWIC',
    label: 'TWIC Card',
    category: 'Licensing',
    entityType: 'DRIVER',
    trackingMode: 'EXPIRY',
    defaultCadenceMonths: null,
    description: 'Transportation Worker Identification Credential (if applicable).',
    sortOrder: 80,
    defaultEnabled: false,
  },

  // ─── TRUCK ──────────────────────────────────────────
  {
    key: 'TRUCK_DOT_INSPECTION',
    label: 'Annual DOT Inspection',
    category: 'Inspection',
    entityType: 'TRUCK',
    trackingMode: 'EXPIRY',
    defaultCadenceMonths: 12,
    description: 'Annual vehicle inspection (§396.17).',
    sortOrder: 10,
    defaultEnabled: true,
    legacyField: 'dotInspectionExpiry',
  },
  {
    key: 'TRUCK_IRP',
    label: 'IRP Registration (Apportioned Plate)',
    category: 'Registration',
    entityType: 'TRUCK',
    trackingMode: 'EXPIRY',
    defaultCadenceMonths: 12,
    description: 'International Registration Plan apportioned plate.',
    sortOrder: 20,
    defaultEnabled: true,
    legacyField: 'irpExpiry',
  },
  {
    key: 'TRUCK_FORM_2290',
    label: 'Form 2290 (HVUT)',
    category: 'Taxes',
    entityType: 'TRUCK',
    trackingMode: 'EXPIRY',
    defaultCadenceMonths: 12,
    description: 'Heavy Vehicle Use Tax — filed annually (Jul–Jun tax year).',
    sortOrder: 30,
    defaultEnabled: true,
    legacyField: 'hvutExpiry',
  },
  {
    key: 'TRUCK_INSURANCE',
    label: 'Insurance',
    category: 'Insurance',
    entityType: 'TRUCK',
    trackingMode: 'EXPIRY',
    defaultCadenceMonths: 12,
    description: 'Liability / cargo / physical damage coverage.',
    sortOrder: 40,
    defaultEnabled: true,
    legacyField: 'insuranceExpiry',
  },
  {
    key: 'TRUCK_IFTA',
    label: 'IFTA License & Decal',
    category: 'Taxes',
    entityType: 'TRUCK',
    trackingMode: 'EXPIRY',
    defaultCadenceMonths: 12,
    description: 'International Fuel Tax Agreement decal (annual).',
    sortOrder: 50,
    defaultEnabled: true,
  },
  {
    key: 'TRUCK_NY_HUT',
    label: 'NY HUT Permit & Decal',
    category: 'Permits',
    entityType: 'TRUCK',
    trackingMode: 'EXPIRY',
    defaultCadenceMonths: 12,
    description: 'New York Highway Use Tax certificate and decal.',
    sortOrder: 60,
    defaultEnabled: false,
  },
  {
    key: 'TRUCK_NM_WDT',
    label: 'New Mexico WDT Permit',
    category: 'Permits',
    entityType: 'TRUCK',
    trackingMode: 'EXPIRY',
    defaultCadenceMonths: 12,
    description: 'New Mexico Weight Distance Tax permit.',
    sortOrder: 70,
    defaultEnabled: false,
  },
  {
    key: 'TRUCK_KY_KYU',
    label: 'Kentucky KYU Permit',
    category: 'Permits',
    entityType: 'TRUCK',
    trackingMode: 'EXPIRY',
    defaultCadenceMonths: 12,
    description: 'Kentucky Weight Distance (KYU) license.',
    sortOrder: 80,
    defaultEnabled: false,
  },
  {
    key: 'TRUCK_OR_WEIGHT_MILE',
    label: 'Oregon Weight-Mile Permit',
    category: 'Permits',
    entityType: 'TRUCK',
    trackingMode: 'EXPIRY',
    defaultCadenceMonths: 12,
    description: 'Oregon weight-mile tax permit.',
    sortOrder: 90,
    defaultEnabled: false,
  },
  {
    key: 'TRUCK_PM',
    label: 'Preventive Maintenance',
    category: 'Maintenance',
    entityType: 'TRUCK',
    trackingMode: 'MILEAGE',
    defaultCadenceMonths: 3,
    description: 'Scheduled preventive maintenance (by date or mileage).',
    sortOrder: 100,
    defaultEnabled: false,
  },

  // ─── TRAILER ────────────────────────────────────────
  {
    key: 'TRAILER_DOT_INSPECTION',
    label: 'Annual DOT Inspection',
    category: 'Inspection',
    entityType: 'TRAILER',
    trackingMode: 'EXPIRY',
    defaultCadenceMonths: 12,
    description: 'Annual trailer inspection (§396.17).',
    sortOrder: 10,
    defaultEnabled: true,
  },
  {
    key: 'TRAILER_REGISTRATION',
    label: 'Registration',
    category: 'Registration',
    entityType: 'TRAILER',
    trackingMode: 'EXPIRY',
    defaultCadenceMonths: 12,
    description: 'Trailer registration / apportioned plate.',
    sortOrder: 20,
    defaultEnabled: true,
  },
  {
    key: 'TRAILER_PM',
    label: 'Preventive Maintenance',
    category: 'Maintenance',
    entityType: 'TRAILER',
    trackingMode: 'MILEAGE',
    defaultCadenceMonths: 6,
    description: 'Scheduled trailer maintenance.',
    sortOrder: 30,
    defaultEnabled: false,
  },

  // ─── COMPANY ────────────────────────────────────────
  {
    key: 'COMPANY_UCR',
    label: 'UCR Registration',
    category: 'Authority',
    entityType: 'COMPANY',
    trackingMode: 'INTERVAL',
    defaultCadenceMonths: 12,
    description: 'Unified Carrier Registration (annual).',
    sortOrder: 10,
    defaultEnabled: true,
  },
  {
    key: 'COMPANY_MCS150',
    label: 'MCS-150 Biennial Update',
    category: 'Authority',
    entityType: 'COMPANY',
    trackingMode: 'INTERVAL',
    defaultCadenceMonths: 24,
    description: 'Biennial DOT number update (MCS-150).',
    sortOrder: 20,
    defaultEnabled: true,
  },
  {
    key: 'COMPANY_IFTA_LICENSE',
    label: 'IFTA License',
    category: 'Taxes',
    entityType: 'COMPANY',
    trackingMode: 'EXPIRY',
    defaultCadenceMonths: 12,
    description: 'Company IFTA license (annual renewal).',
    sortOrder: 30,
    defaultEnabled: true,
  },
  {
    key: 'COMPANY_IFTA_QUARTERLY',
    label: 'IFTA Quarterly Filing',
    category: 'Taxes',
    entityType: 'COMPANY',
    trackingMode: 'INTERVAL',
    defaultCadenceMonths: 3,
    description: 'Quarterly IFTA fuel tax return.',
    sortOrder: 40,
    defaultEnabled: true,
  },
  {
    key: 'COMPANY_MC_AUTHORITY',
    label: 'MC Operating Authority',
    category: 'Authority',
    entityType: 'COMPANY',
    trackingMode: 'EXPIRY',
    defaultCadenceMonths: null,
    description: 'FMCSA operating authority status.',
    sortOrder: 50,
    defaultEnabled: true,
  },
  {
    key: 'COMPANY_BOC3',
    label: 'BOC-3 Process Agents',
    category: 'Authority',
    entityType: 'COMPANY',
    trackingMode: 'EXPIRY',
    defaultCadenceMonths: null,
    description: 'BOC-3 blanket process agent filing.',
    sortOrder: 60,
    defaultEnabled: false,
  },
];

export const CATALOG_BY_KEY = new Map(COMPLIANCE_CATALOG.map((t) => [t.key, t]));

/** Legacy denormalized fields backfilled into compliance records. */
export const LEGACY_BACKFILL = COMPLIANCE_CATALOG.filter((t) => t.legacyField);
